name: "Coding standards"

on:
  push:
    paths:
      - '**.php'
      - 'linter.sh'
      - 'phpstan.neon'
      - 'phpcs.xml'
      - '.github/workflows/coding-standards.yml'
  pull_request:

jobs:
  validate-composer:
    name: Validate composer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Validate composer packages
        run: composer validate

  validate-php:
    name: Validate PHP
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install composer packages
        run: composer install

      - name: Run linters
        run: ./linter.sh

  security-check:
    name: Security check
    runs-on: ubuntu-latest
    needs: [ validate-composer, validate-php ]

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run security checker
        run: composer audit

  test-coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    needs: [ validate-composer, validate-php ]

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install composer packages
        run: composer install

      - name: Run test coverage
        run: composer test-coverage
