name: "Tests"

on:
  push:
    paths:
      - '**.php'
      - 'phpunit.xml'
      - '.github/workflows/run-tests.yml'
  pull_request:

jobs:
  test-coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install composer packages
        run: composer install

      - name: Run test coverage
        run: composer test-coverage
