name: "Update Changelog"

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Create and checkout changelog branch
        run: |
          git fetch origin changelog || true
          if git show-ref --quiet refs/remotes/origin/changelog; then
            git checkout changelog
            git pull origin changelog
          else
            git checkout -b changelog
            git push -u origin changelog
          fi

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
          push_options: --force-with-lease

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: changelog
          base: main
          title: "Update CHANGELOG.md"
          body: "Automated changelog update after release."
          delete-branch: false
