name: "Update Changelog"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create and checkout changelog branch
        run: |
          git fetch origin changelog || true
          if git show-ref --verify --quiet refs/heads/changelog; then
            git checkout changelog
            git pull
          else
            git checkout -b changelog
            git push -u origin changelog
          fi

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: changelog
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update CHANGELOG
          branch: changelog
          base: main
          title: "Update CHANGELOG.md"
          body: "Automated changelog update after release."
