name: "Validate PHP"

on:
  push:
    paths:
      - '**.php'
      - 'linter.sh'
      - 'phpstan.neon'
      - 'phpcs.xml'
      - '.github/workflows/validate-php.yml'
  pull_request:

jobs:
  validate-composer:
    name: Validate composer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Validate composer
        run: composer validate

  validate-php:
    name: Validate PHP
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run linters
        run: ./linter.sh

  security-check:
    name: Security check
    runs-on: ubuntu-latest
    needs: [ validate-composer, validate-php ]

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: pcov

      - name: Make composer.lock readable
        run: cp composer.lock ../composer.lock

      - name: Run security checker
        uses: symfonycorp/security-checker-action@v5

  tests-coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    needs: [ validate-composer, validate-php ]

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run test coverage
        run: composer test-coverage
